### ISSUE TITLE
更動匯出所下載的資料夾，會造成匯出失敗

### ISSUE THREAD

**Issue by penguinfuko** [tongwentang/tongwentang-extension#1]
1. os 版本： win10 1803
2. firefox 版本：70.0b4（64 位元）（beta版）
3. 新同文堂版本：0.6.0

- 在未輸入任何內容，亦未改變下載位置時→匯出成功
- 在輸入自訂字串，未改變下載位置時→匯出成功
- 在輸入自訂字串，更改下載位置→匯出失敗
- 在設定清空，並且只保留一個擴充的情況下，更改下載位置→匯出失敗

目前從桌面、文件、圖片，或音樂等等的資料夾都無法匯出。只有預設的下載資料夾成功。

**Comment by t7yang** [comment]
OK，有時間我再看看。那個...不是新同文堂的版本，你直接寫開發代號就好了。

**Comment by t7yang** [comment]
這個問題應該解決了，還有發生請留言。
