### ISSUE TITLE
cannot change brackets

### ISSUE THREAD

**Issue by mojibiz00** [tongwentang/tongwentang-extension#11]
cannot change traditional brackets to simplified brackets. for example, 「」to “”.

**Comment by t7yang** [comment]
Could you confirm this issue is fixed on 2.1.1?
I can not reproduce it.

**Comment by mojibiz00** [comment]
still problem ringer on 2.1.1.  traditional 「」to simplified  “”.

**Comment by t7yang** [comment]
close #11 by https://github.com/tongwentang/tongwen-core/commit/5fdbd5be3d1b2fa31b4ce3ea35e652caa724abb3
