### ISSUE TITLE
Not working in Vivaldi. 在 Vivaldi 瀏覽器不起效。

### ISSUE THREAD

**Issue by jasonlam-swatow** [tongwentang/tongwentang-extension#12]
自動更新至 2.1 後，在 Vivaldi 瀏覽器（最新版 3.7.2218.52）自動轉換、手動單擊圖示轉換均無效。

**Comment by t7yang** [comment]
我知道有這個問題，但目前沒有人力去維護除了 GC 跟 FX 以外的瀏覽器。有能力的話請協助找出可能的問題，這樣我或許可以修復。

**Comment by waynejhou** [comment]
稍微追了一下
錯誤是出現在
https://github.com/tongwentang/tongwentang-extension/blob/master/src/content/services/get-detect-lang.ts
`return runtime.sendMessage(msg).then(({ payload }: BgActDetectLang) => payload);`
我不太清楚這事實上是到哪裡的功能 但是 只要 加個 catch 就可以了
`return runtime.sendMessage(msg).then(({ payload }: BgActDetectLang) => payload).catch((err)=>{console.log(err); return ZhType.und;});`
不過 要是有用到這段程式的功能可能就不起作用

**Comment by waynejhou** [comment]
希望能快點 patch
(Vivaldi 愛好者

**Comment by t7yang** [comment]
😨 Vivaldi 居然有沒有偵測語言的 API 嗎？你可以幫我確認這件事情嗎？

**Comment by waynejhou** [comment]
抱歉 ..我對開發擴充元件這塊不熟 只是稍微會一點 ts
不太清楚相關的關鍵字

**Comment by t7yang** [comment]
沒關係，不過理論上你的做法應該是沒問題的，我再補上去。
