### ISSUE TITLE
要不要考慮往 Microsoft Edge Chromium 與 Opera 的商店也同時提供這個 Chrome Addon？ 

### ISSUE THREAD

**Issue by ShikiSuen** [tongwentang/tongwentang-extension#14]
最近看到這款 Addon 有在更新，所以就想順便講講這個事情。

另外，請問可否幫忙關閉下面這個 issue？一直open的話我這邊會有關不掉的提示：
https://github.com/tongwentang/New-Tongwentang-for-Chrome/issues/20

**Comment by ShikiSuen** [comment]
(原因在於 Chrome 線上商店在中國大陸無法使用，僅此而已。)

**Comment by t7yang** [comment]
> 
> 
> (原因在於 Chrome 線上商店在中國大陸無法使用，僅此而已。)

目前沒有打算。

> 
> 
> 最近看到這款 Addon 有在更新，所以就想順便講講這個事情。
> 
> 另外，請問可否幫忙關閉下面這個 issue？一直open的話我這邊會有關不掉的提示：
> [tongwentang/New-Tongwentang-for-Chrome#20](https://github.com/tongwentang/New-Tongwentang-for-Chrome/issues/20)

已關閉所有 issue 跟 pr 。

**Comment by t7yang** [comment]
Edge 審核中。

**Comment by t7yang** [comment]
https://microsoftedge.microsoft.com/addons/detail/%E6%96%B0%E5%90%8C%E6%96%87%E5%A0%82/ijddgmclgedepadbikmfekambhhfjfnl
