### ISSUE TITLE
支援將舊版設定匯入到新版

### ISSUE THREAD

**Issue by doggy8088** [tongwentang/tongwentang-extension#15]
舊版新同文堂已經存在許多時日，舊版的設定與自訂詞彙是否可以讓舊用戶可以順利匯出並匯入到新的「新同文堂」擴充套件中？

**Comment by t7yang** [comment]
理論上可以，但是不知道為什麼 chrome 版的有問題。

**Comment by doggy8088** [comment]
以前有 symbolS2T 與 symbolT2S 的設定，新版不需要了嗎？

**Comment by t7yang** [comment]
其實是否是標點符號不重要，都是轉換的詞彙，所以我捨棄這塊了。

**Comment by doggy8088** [comment]
新版的 Domain Rules 好像不夠用，因為我舊版的 URL pattern 有包含 path 部分，很多網站都會透過路徑切換多國語言版。
![image](https://user-images.githubusercontent.com/88981/114588761-9ce3f500-9cb9-11eb-8282-c63e12f0e04f.png)

**Comment by t7yang** [comment]
怎麼說？基本上如果是純文字的話，只要 url 有符合（不管是在哪裡）都會視為需要轉換。

所以你規則寫 `istio.io/zh` 的話，任何 url 有存在一樣的字串就會被認為符合該規則的網址。

如果覺得不夠用，就請輸入正規表示法。

https://github.com/tongwentang/tongwentang-extension/blob/master/docs/preferences/preferences_zh-tw.md#%E7%B6%B2%E5%9F%9F%E8%A6%8F%E5%89%87
