### ISSUE TITLE
建議 GitHub Repo 可以補上連結

### ISSUE THREAD

**Issue by doggy8088** [tongwentang/tongwentang-extension#16]
建議 [舊版的 Repo](https://github.com/tongwentang/New-Tongwentang-for-Chrome) 可以更新到新的連結：
![image](https://user-images.githubusercontent.com/88981/114589142-f8ae7e00-9cb9-11eb-9330-8c149fec0094.png)

新版 Repo 也建議加上 Chrome extension 的連結: https://chrome.google.com/webstore/detail/new-tongwentang/ldmgbgaoglmaiblpnphffibpbfchjaeg?hl=zh-TW
![image](https://user-images.githubusercontent.com/88981/114589242-124fc580-9cba-11eb-8a0f-1cd8228be608.png)

**Comment by t7yang** [comment]
README 已經有更新。 about 我會再拿掉，那是之前作者完全沒有更新 about 。
套件中心的連結我會再新增，目前是任何瀏覽器的連結都沒加，一視同仁。

**Comment by doggy8088** [comment]
我從新版 Repo 的 README 沒看到有任何 extensions 的連結，建議可以加上

https://github.com/tongwentang/tongwentang-extension/blob/master/README.md

**Comment by t7yang** [comment]
嗯嗯，我上面回覆已經有提到囉，套件中心的連結我會再新增。
