### ISSUE TITLE
Miss translation

### ISSUE THREAD

**Issue by Justinwang677** [tongwentang/tongwentang-extension#17]
This is very minor but for the word 胡萝卜, it translates to 胡蘿卜 it should be 胡蘿蔔

**Comment by t7yang** [comment]
The current built-in dictionary is not compatible any more for the new converter `tongwen-core`.

Please join and make contribution to the new dictionary project on
https://github.com/tongwentang/tongwen-mapping/issues/1

**Comment by yaoziyuan** [comment]
In Simplified Chinese, "干隆" should be "乾隆".
In Simplified Chinese, "着名" should be "著名".

**Comment by yaoziyuan** [comment]
能否先在 extension 里改正这两例？这两个词在简体中文里，是"乾隆"和"著名"，不是"干隆"和"着名"。
