### ISSUE TITLE
右鍵菜單的剪貼版轉換不見了

### ISSUE THREAD

**Issue by freezewind** [tongwentang/tongwentang-extension#18]
更新後，右鍵菜單的剪貼版轉換不見了

WIN10
Firefox ESR 78.9.0
New Tong Wen Tang 2.1.1

**Comment by t7yang** [comment]
https://github.com/tongwentang/tongwentang-extension/blob/master/CHANGELOG.md#changed-2

**Comment by freezewind** [comment]
@t7yang 
所以說從菜單中移除剪貼版轉換是故意的，而且並沒有加回去的想法嗎？
因為我沒有把新同文堂的Browser Action icon放在toolbar上，並且右鍵菜單能夠在網頁的任何位置上使用，比用Browser Action icon更加方便。
能不能考慮一下加回去呢？

還有一個小問題，從那裏能看到default shortcut？我從擴展的說明和設定都看不到default shortcut。

**Comment by t7yang** [comment]
我不是廚師，不做菜，沒有菜單。

轉換剪貼簿的行為跟頁面本身是脫鉤的，本來就不應該放在網頁的右鍵選單中，這使得在內建頁面或其他套件產生的頁面中反而無法使用，之前的作者要把它塞在那裡反而才是不對的做法。

所以除非你可以給出非常充分而且合理的理由，那我會考慮，如果僅僅只是因為習慣的問題，我就不會加回去。
否則哪天某個使用者跳出來說用滑鼠手勢轉換更加方便，我就沒完沒了了。

這是 Firefox 的 UX 問題，Chrome 也沒有好到哪裡就是了
![image](https://user-images.githubusercontent.com/4502661/114802183-d73fb600-9dcf-11eb-83b7-4075939c5a5c.png)

**Comment by freezewind** [comment]
謝謝你快速的回答。
我只是問一下有沒有加回來的可能性，不行就算了。
關於shortcut方面，是我完全沒有注意到這個選項，麻煩你截圖了。
(我覺得FireFox和Chrome的UX都不怎麼好，不過也沒有什麼好選擇就是了。)
