### ISSUE TITLE
kiwi browser中旧版本会自动转换为简体  更新后突然失效

### ISSUE THREAD

**Issue by RenShine** [tongwentang/tongwentang-extension#19]
如题  kiwi brwoser是安卓手机中唯一支持使用chrome插件的浏览器

**Comment by t7yang** [comment]
應該就是他們的 chromium 版本太舊。這種小眾的瀏覽器我真的不是很有精力去處理，如果你有辦法知道是什麼問題，那我可以考慮處理。
