### ISSUE TITLE
自動轉換設定不會儲存(chrome)

### ISSUE THREAD

**Issue by ted1030** [tongwentang/tongwentang-extension#22]
瀏覽器版本:Chromium 86.0.4240.198
新同文堂版本:2.1.1
有看到之前也有人發這個問題，但是我這邊的問題依舊存在，
開啟瀏覽器->在新同文堂的自動轉換設定選擇偵測式簡轉正->關掉並重開瀏覽器->看到自動轉換設定變成停用

**Comment by t7yang** [comment]
請提供更多資訊，包含使用的版本及具體如何重現。
