### ISSUE TITLE
若環境中沒有 chromium 則無法使用 debug mode 進行開發

### ISSUE THREAD

**Issue by ensky** [tongwentang/tongwentang-extension#26]
#21 的 PR 被 reject 了，因此希望提出來討論一下比較合理的作法，再動手。

以我這邊的開發環境，我需要 webpack watch，但我沒有 chromium (在 Windows WSL2 裡面，暫時不想架 X window)，我的開發劉程是：
1. WSL webpack watch + build
2. chrome extension 直接掛載 dist directory，reload 即可看到結果

目前 `yarn dev:chromium` 一定要有 chromium 的情況下我只能修改 package.json 或 webpack.config.js 來達成我要的功能，但如果可以的話支援在沒有 chromium 的情況下仍然可以開發可能還是比較好？

**Comment by t7yang** [comment]
基於目前的專案尚未有測試案例，所以唯一能夠驗證程式正確性的機制只有下列幾種：

1. TypeScript 嚴格型別測試。
2. Linting。
3. 實際執行套件並人工測試。

所以我不懂你為什麼一定要經過 webpack watch 才能開發。

如果你真的不想要人工測試的部分，請執行 `yarn test:tsc --watch` 讓 TypeScript 驗證你的程式碼（同時執行 lint watch），這樣速度也是最快的。

但因為沒有測試案例，所以無論如何最好實際執行來確認你的異動是否行為正常。

另外， webpack cli flag 的權重是比 config 要來得高的，如果你真的堅持要用 webpack watch 就用 `yarn build:chromium --watch` ，這樣也可以達到你要的效果。

有其他疑問的話，歡迎再提出來討論，我先關閉。
