### ISSUE TITLE
请问为什么我安装后是英文版本的？

### ISSUE THREAD

**Issue by zhouhuajdsh** [tongwentang/tongwentang-extension#28]
如何使用中文版本？
![Snipaste_2021-04-25_08-36-03](https://user-images.githubusercontent.com/29763911/115976508-5dfb4c80-a5a1-11eb-9f4d-e16d44e3f764.jpg)

**Comment by t7yang** [comment]
瀏覽器根據你的介面語言選擇的，跟套件無關。
這種問題在 dicussions 提問就好，不用開 issue 。

**Comment by zhouhuajdsh** [comment]
我确定我的介面语言是中文，我又重新用google的chrome官方中文版试了下，安装后还是显示英文的。还是请作者确认一下吧

**Comment by t7yang** [comment]
我不知道為什麼 Chrome 不會 fallback 回中文，我記得以前用 chrome 的時候一些套件都會很雞婆的簡體，但沒有簡體的話他居然會強制用 en 而不是鄰近的 zh-TW 。

但 Firefox 就沒有這個問題。
![image](https://user-images.githubusercontent.com/4502661/116085139-14aa1a80-a6d1-11eb-9c22-d07f277b81b3.png)
