### ISSUE TITLE
When using auto mode in overleaf, latex code in textarea jumps around

### ISSUE THREAD

**Issue by benhaotang** [tongwentang/tongwentang-extension#3]
I always turn on auto simplify to traditional, but it seems that after this update, when I try to write latex on overleaf, all my code in the textarea just jump around and i cannot type anything until I disable your extension for the site. In older version i have never encounter such problem.

**Comment by t7yang** [comment]
![image](https://user-images.githubusercontent.com/4502661/113382555-55ee2980-93b4-11eb-9ec9-6ec1221fdd8b.png)
Please turn off "Dynamic Convert", the new "Dynamic Convert" feature is aim to support Single Page Application website which dynamically update web page content without refresh web page. When this feature on, the extension will keep track and convert the change of page content.

If you still want to enjoy the new Dynamic Convert feature, you can consider either one:
1. Add a domain rule for overleaf and set target to disabled (this can simply done by right click the extension icon when browsing overleaf).
2. Change the "Auto Convert" to "Detective Simplified to Traditional", then extension will check the web page content language before convert, if not target language then extension just do nothing.

**Comment by benhaotang** [comment]
Thanks
