### ISSUE TITLE
自動轉換設定不會儲存(Firefox)

### ISSUE THREAD

**Issue by thomasho18** [tongwentang/tongwentang-extension#30]
更新到2.1.2後，發現設定為"偵測式簡轉正"設定還是不會儲存
disable再enable還是會跳回"停用"

**Comment by t7yang** [comment]
我目前無法重現這個問題。請提供更多的資訊。或是你有辦法用一個 portable 版的 Firefox 重現這個問題然後傳送給我。

**Comment by thomasho18** [comment]
設定成這樣:
![圖片](https://user-images.githubusercontent.com/13509164/116262195-ea2c9000-a7aa-11eb-947b-0e273fc77a70.png)
然後關掉firefox，再打開firefox，設定會變為:
![圖片](https://user-images.githubusercontent.com/13509164/116262472-252ec380-a7ab-11eb-8d5e-b0eac6eb1c25.png)
Firefox版本:
![圖片](https://user-images.githubusercontent.com/13509164/116262608-468faf80-a7ab-11eb-92df-79548b2689ff.png)

**Comment by t7yang** [comment]
我真的測試不出來，如果真的沒有成功存入的話，是不會成功轉換的。

![image](https://user-images.githubusercontent.com/4502661/116264632-07faf480-a7ad-11eb-9b7d-a27c90b5318a.png)

**Comment by thomasho18** [comment]
不好意思，跟您確認一下，您設定成"偵測式簡轉正"後，有將firefox整個關閉，再打開測試嗎?
您那邊的設定還是沒有跑回"停用"?

**Comment by t7yang** [comment]
> 不好意思，跟您確認一下，您設定成"偵測式簡轉正"後，有將firefox整個關閉，再打開測試嗎?
> 您那邊的設定還是沒有跑回"停用"?

好，已確認問題。


> 對了，我是在firefox addon網站下載plugin的，這會有差異嗎?

沒有，套件本來就應該從 addons 中心下載。

**Comment by thomasho18** [comment]
更新到2.1.3後正常，非常感謝!
