### ISSUE TITLE
在语雀文档里因为光标抖动导致无法输入的问题

### ISSUE THREAD

**Issue by cuikai-wh** [tongwentang/tongwentang-extension#31]
在语雀文档里编辑时，遇到的问题。https://www.yuque.com/

视频：
https://drive.google.com/file/d/1WbM8JX3enttmnxlKxLBDhpVONyNIpt7v/view?usp=sharing

动图：
![image](https://user-images.githubusercontent.com/2498715/116338992-3f01f200-a80f-11eb-8c62-0a35679809ab.png)

macOS Big Sur 11.2.3 (20D91)
Chrome 版本 90.0.4430.85（正式版本） (x86_64)

注，Safari 版本14.0.3 (16610.4.3.1.7)，无此问题。

————

经过语雀技术同学的指导，定位到可能是此插件的问题。把此插件关闭，或者开启时把相关域名屏蔽后，可以解决问题。
尝试过关闭「文本框内自动简繁转换」（Textarea Simplified to Traditional / Textarea Traditional to Simplified），但问题依旧。

————

以上信息供参考，希望能尽快解决哦。

**Comment by t7yang** [comment]
可以先關閉動態轉換，套件上架不會這麼快。
