### ISSUE TITLE
起點中文網自動簡轉繁不會生效

### ISSUE THREAD

**Issue by darkwang2003** [tongwentang/tongwentang-extension#32]
在起點看小說的時候不知道什麼原因每個章節都要重覆按一次小圖示才會轉換，改版前是正常的。
是否要將自動轉換的時間延後兩秒試試?
感覺是轉換的時機過早，網頁還沒讀完?

**Comment by t7yang** [comment]
沒有發現有任何問題。

回報問題請提供所有可能的資訊，連結、設定檔、如何重現，不然完全無法知道你怎麼碰到的。

**Comment by darkwang2003** [comment]
因為有時候會發生，有時候不會發生，所以很難把狀況重現出來。
狀況發生時也可以選擇按F5，重新讀一次網頁，這樣就會轉繁體了。
狀況發生時通常都是網頁內的文字讀取較慢的情況。
設定檔就是一般的預設設定，只是把起點首頁加入簡轉繁網域而已。

目前已經灌回1.5版，一切正常，暫時等新版穩定再更新上去。

**Comment by t7yang** [comment]
沒有穩不穩定，因為現在沒有發現任何問題，如果沒有找到重現問題的步驟，那就談不上修復，因為連是不是套件的問題都無法確定。

**Comment by darkwang2003** [comment]
好的，辛苦了。
目前僅將2.1.3轉為1.5版，一切恢復正常。
多謝您花時間去檢查，也祝您順心。
