### ISSUE TITLE
無法自定繁簡中轉換後字型

### ISSUE THREAD

**Issue by sunnymiu** [tongwentang/tongwentang-extension#34]
各位好，

舊版同文堂提供繁簡中文字型轉換，這樣例如瀏覽簡轉繁後網站可以用繁中字型顯示網頁，避免好像宋體顯示繁中文字、出現簡中符號等錯誤。功能似乎在新一版本移除了，請問有機會重新補上嗎？

謝謝！

**Comment by t7yang** [comment]
請先搜尋相關 issue #4  ，如果是問題的話請用 discussions 發文。
