### ISSUE TITLE
新版同文堂沒法繁簡轉換標點符號

### ISSUE THREAD

**Issue by ArimaniZeon** [tongwentang/tongwentang-extension#36]
詞彙＞自訂正轉簡，輸入「 => "，」 => "，『 => '，』 => '
然後依然無法轉換

村雨故作驚訝問：「甚麼？老闆想掃我出門口嗎？」
網頁正轉簡
村雨故作惊讶问：「甚么？老板想扫我出门口吗？」

舊版是會將引號轉換，新版反而倒退取消了。

在Firefox插件評論留言，然後說**開發者**說**這裡留言不會通知作者**，Emmmmmm你那個開發者是假的嗎？我遇上假的開發者和假的插件？

回報問題又只能在Github，沒有其他渠道嗎？硬是被迫因為一個問題而申請一個會員帳戶，而且之後可能不會再用的帳戶，煩

**Comment by t7yang** [comment]
問題已經修復 96bff081e95d05098cc39e506118b795e929fb1c 但尚未發布新版本。

我確實是沒有收到留言的通知，是否是假的開發者，留給你自己判斷。如果你覺得假的，請不要用，趕快刪除套件。

連 Firefox 的網站都設計的技術支援訊息的欄位，技術支援懂嗎？你去買東西遇到問題也是請你打電話給客服，難道你要靠北為什麼不能打電話人資回報問題嗎？事情有分類型，每一種類型有他處理的方式。軟體開發是一項技術工作，有我們的工作流程，如果你是外行人不懂，我不怪你，但請不放尊重一點。這是開放原始碼專案，開發者跟你之間沒有權利義務關係懂嗎？

如果你很不爽，沒問題，我送你五個字——不爽不要用。

**Comment by ArimaniZeon** [comment]
感謝，我會刪除套件，畢竟用戶沒有權利義務向開發者回儹使用意見及BUG，不爽真的可以不用。

![https://imgur.com/DsEde62](https://imgur.com/DsEde62)

早於舊版時轉換就常常跳出亂碼，一直都沒有說。新版功能倒退了，向「開發者」回報，卻討來這回應，還真是有夠尊重。
我相信我的中文能力沒有問題，懂得區分「開發者」和「技術支援」有何分別。如果廿四天前是「技術支援」回應，我應該不會那麼惱火。
還有申明一點，如果我去買東西遇到問題也是請你打電話給客服，我當然不會靠北為什麼不能打電話人資回報問題，因為我知道打給客服他們會向有關方面回報受理事件，而不是說「我們這邊不會處理也不會轉介問題」。
