### ISSUE TITLE
建議把clipboard的功能還原

### ISSUE THREAD

**Issue by sean-yang** [tongwentang/tongwentang-extension#40]
舊版有的，不知為何將它拿掉，個人是很需要這個功能的，如果能把它加回去會十分感激！

**Comment by t7yang** [comment]
新版從來就沒有拿掉，不管是從選單（移至圖示選單）還是從快捷鍵，都可以。

**Comment by sean-yang** [comment]
不好意思，很少用那個email account，所以隔這麼久才回。好吧，這是圖

https://imgur.com/HxNGRvs

是不是我少設了什麼東西？我用firefox！

**Comment by t7yang** [comment]
在右上角的套件圖示中，或是用快捷鍵都可以。

**Comment by sean-yang** [comment]
看到了，謝謝即時回答。我記得以前在網頁按右鍵就會跑出該選項，可不可以考慮再把它們加回去，謝謝！

**Comment by t7yang** [comment]
剪貼簿轉換不依賴網頁，放在網頁右鍵選單反而奇怪，所以才移到套件圖示。

**Comment by sean-yang** [comment]
瞭解，謝謝說明！
