### ISSUE TITLE
關於"Auto Convert" feature問題

### ISSUE THREAD

**Issue by aten0724** [tongwentang/tongwentang-extension#42]
打開了auto convert的Simplified to Traditional (Detective)，頁面會自動把簡體字轉成繁體字，但是不包括特別字
比如說簡體字『列标签』轉成繁體字『列標簽』，其中『簽』字要再按插件的icon才會變成『籤』字
想問一下就是auto convert遺漏了轉特別字的部分嗎? 還是說這是有意為之? 謝謝開發人員 辛苦了

**Comment by t7yang** [comment]
辭庫的問題，目前套件使用的辭庫不是針對現在的引擎設計的，所以有這種情況。
