### ISSUE TITLE
自訂詞彙有時沒有作用

### ISSUE THREAD

**Issue by jeeyi345** [tongwentang/tongwentang-extension#44]
我透過之前建議的方式，在設定json找到詞彙 json 部分
匯入了來自以下專案的簡繁詞彙
https://github.com/pjchender/cn2tw4programmer

![image](https://user-images.githubusercontent.com/12745397/135951676-36e776b5-d1ce-4aab-a157-5d2cb1c550c8.png)
但在如下有用在詞彙表裡的，幾乎都沒有作用
https://learn.freecodecamp.one/
https://www.w3school.com.cn/
只有發現『算法』會變成『演算法』
其他如
面向對象>物件導向
變量>變數 ... 等等都沒有作用
不曉得哪邊有問題，請幫忙看看，謝謝

**Comment by t7yang** [comment]
我目前使用上沒有遇到問題。
你最後匯入的設定檔可以提供出來嗎？這樣我才能夠幫你測試。

然後你自己也可以建立一個新的 Firefox profile 來測試在乾淨環境下是否有問題。

**Comment by jeeyi345** [comment]
在 firefox 匯入，還是只有演算法有用，其他不行 :(

有注意到手動添加的教程>教學有用，其他沒有用

以下提供匯入的設定檔:
[tongwentang-pref(教程ok).json.txt](https://github.com/tongwentang/tongwentang-extension/files/7290813/tongwentang-pref.ok.json.txt)

**Comment by t7yang** [comment]
問題出在你的「轉換目標原文」不是簡體，v2.0 之後採用新的轉換核心，演算法也重寫設計過，所以原文必須是簡體，這樣才會有效過。你把原文改成簡體可以了。
