### ISSUE TITLE
建議將.tw以及.hk預設列為不轉換

### ISSUE THREAD

**Issue by t0rnapart** [tongwentang/tongwentang-extension#47]
建議將.tw以及.hk預設列為不轉換繁簡。並在白名單中添加wildcard"*"的使用法，以便使用者直接過濾某網域的繁簡設定，謝謝！

**Comment by t7yang** [comment]
> 建議將.tw以及.hk預設列為不轉換繁簡。

雖然可能簡體的使用者已經不多，但這個套件並非只服務正體的使用者。所以這種預設的行為不恰當，我也不會考慮這麼做。任何自訂的規則都由使用者自行負責新增。

網域規則已經有相關文件
https://github.com/tongwentang/tongwentang-extension/blob/master/docs/preferences/preferences_zh-tw.md#%E7%B6%B2%E5%9F%9F%E8%A6%8F%E5%89%87

但目前在設定頁面未有提及，這點在未來會改進。
