### ISSUE TITLE
Should we have a branch with built code

### ISSUE THREAD

**Issue by Rplus** [tongwentang/tongwentang-extension#5]
是否考慮開個 build 過的 branch 呢？

部份使用者不喜歡從 Store 裝來用(因為會強制自動更新)
有的會自己拉 repo 下來用載入未封裝的形式使用 extension
![image](https://user-images.githubusercontent.com/1808835/113438475-39390c80-941b-11eb-92e0-5a36e44c8561.png)

**Comment by t7yang** [comment]
嗯……我是有寫了 [build instruction](https://github.com/tongwentang/tongwentang-extension/blob/master/docs/build/readme.md) ，所以其實只需要根據 build instruction 去 build 就可以得到組建後的資源檔。

我自己是覺得不太有必要，而且我也不是很喜歡把 build result 放到 git 。

可能要研究一下 CI/CD 怎麼去把 build resources 放到 release 那裏，這塊我不是很熟，需要再研究。

**Comment by danny0838** [comment]
可以考慮開在 `gh_pages` branch 還可以加上一兩個目錄網頁一起發布。

**Comment by t7yang** [comment]
> 
> 
> 可以考慮開在 `gh_pages` branch 還可以加上一兩個目錄網頁一起發布。
> 
> 不然在 GitHub 還有個正規做法是把 Tag 加上說明和編譯檔弄成 Release 。

後者是我認為比較理想的方式，有什麼參考資源嗎？

**Comment by kylechiang1** [comment]
新版無法導入自定義轉換詞彙和網站列表，此前積累的用戶偏好不敷使用，需手動添加，希望開放導入功能。

**Comment by danny0838** [comment]
@t7yang 如果沒有特殊需求應該 [RTFM](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) 就可以了XD

不過 Release 雖然看起來比較正式，缺點是似乎沒有納入 Git 版控。總之看人啦。

**Comment by t7yang** [comment]
> 
> 
> @t7yang 如果沒有特殊需求應該 [RTFM](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) 就可以了XD
> 
> 不過 Release 雖然看起來比較正式，缺點是似乎沒有納入 Git 版控。總之看人啦。

真的要說 release 就是套件中心經過審核跟簽章的版本

**Comment by t7yang** [comment]
> @kylechiang1 
> 
> 新版無法導入自定義轉換詞彙和網站列表，此前積累的用戶偏好不敷使用，需手動添加，希望開放導入功能。

你用一個免安裝的 Firefox/Chrome 安裝舊版的匯入之後再匯出完整的版本，再拿到新版的去匯入，新版支援匯入之前的設定。
