### ISSUE TITLE
Error happens when I tried to add New Tong Wen Tang in Firefox add-ons.

### ISSUE THREAD

**Issue by woodencomb** [tongwentang/tongwentang-extension#50]
I have no issue adding New Tong Wen Tang in Firefox until about two weeks ago. I was trying setup my new laptop and tried to add New Tong Wen Tang in Firefox add-on, I got this error message "An unexpected error occurred during installation."

Both Firefox and New Tong Wen Tang are latest version and they are 96.0.3 (64-bit) and 2.1.4 respectively. 

I can not use chrome because if I used Chrome to open a simplified Chinese file and web change simplified to traditional Chinese didn't work either. 

![Screen Shot 2022-01-28 at 11 25 30 AM](https://user-images.githubusercontent.com/98615505/151610802-cff84c56-eb38-42eb-bf6a-d5e435bbf89d.png)

Please help!!

**Comment by t7yang** [comment]
Have u ever try to install in a fresh new profile firefox?

**Comment by woodencomb** [comment]
First, thank you for responding. 
No, I didn't create a new profile in FIrefox. Firefox is not my default browser. I used it mostly for add-on so I use it as default. I didn't sign-in either.

**Comment by t7yang** [comment]
Please try to install TongWenTang in a fresh new profile in order to make sure the issue is no caused by your  profile.
