### ISSUE TITLE
“著”字的简化方法

### ISSUE THREAD

**Issue by yaoziyuan** [tongwentang/tongwentang-extension#52]
“著”既是一个简体字（如“著作”、“著名”）也是一个繁体字（如繁体“他看著我”应该简化为“他看着我”）。

我估计老版的新同文堂对这个字的简化是这样处理的：“著”默认一律简化成“着”（如“他看著我”），但如果在“著作”、“著名”等单词里则保留原形。也就是说，先尝试匹配“著作”、“著名”等单词（此时转换成原样，也就是“著作”、“著名”），如果都匹配不到才匹配“著”这个字（此时转换成“着”）。

**Comment by t7yang** [comment]
轉換錯誤的問題請看 pinned issue，如果單純想討論請用 discussion 。
https://github.com/tongwentang/tongwentang-extension/issues/17
