### ISSUE TITLE
Quotes wrongly translated ' -> 』

### ISSUE THREAD

**Issue by alabamagan** [tongwentang/tongwentang-extension#56]
In correctly translate quotes to Chinese quotes.
' -> 』 even in words like: that's -> that』s

**Comment by t7yang** [comment]
1. duplicated https://github.com/tongwentang/tongwentang-extension/issues/54#issuecomment-1224327851
2. dictionary issues should file on https://github.com/tongwentang/tongwen-dict

**Comment by t7yang** [comment]
should be fine on 2.1.6
