### ISSUE TITLE
Extension mistakenly converting english quote for theverge.com

### ISSUE THREAD

**Issue by ICHx** [tongwentang/tongwentang-extension#57]
Platform:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101

Test Link: https://www.theverge.com/2021/5/31/22461871/google-photos-compression-comparison-storage

Disabled Plugin:
![圖片1](https://user-images.githubusercontent.com/11556527/186716213-b2c8e950-256b-4dcc-9748-e56ec4d383b2.png)

Enabled auto simp to trad:
![圖片2](https://user-images.githubusercontent.com/11556527/186716243-4688d70b-100c-416a-99ce-db891f00a69e.png)

**Comment by t7yang** [comment]
https://github.com/tongwentang/tongwentang-extension/issues/54#issuecomment-1222787468

**Comment by t7yang** [comment]
should be fine on 2.1.6
