### ISSUE TITLE
怎麼樣可以只轉換簡繁，而不轉換用詞

### ISSUE THREAD

**Issue by yanrs17** [tongwentang/tongwentang-extension#61]
舉例來說，
現在：数组->陣列
希望：数组->數組

怎麼感覺之前沒有遇到過，最近突然就出現了？

**Comment by t7yang** [comment]
Array 台灣本來就叫陣列，中國才叫數組。
台灣很多人整天看中國文章，連台灣自己的辭彙都不會講。

但是這個詞彙屬於高汙染的詞彙，辭庫 repo 下次會先拿掉。
以後辭庫的問題請到辭庫 repo 回報。
https://github.com/tongwentang/tongwen-dict

**Comment by yanrs17** [comment]
我不是台灣人，我雖然用正體，但看不太懂台灣用詞

**Comment by t7yang** [comment]
了解，更多辭庫自訂的選項會在未來慢慢實作。
我有這樣的想法，但礙於專案只有我一個人在開發，所以只能等待未來有時間慢慢處理。

但提供在地化服務是一直是最重要的宗旨之一，目前也符合絕大多數使用者的需求。
在此期間，如果因力所未及導致你使用上的不適應，也可以考慮先轉用其他方案（我知道有其他套件有提供相同的服務）。
只能說聲抱歉，因為我實在沒辦法跟你保證什麼時候可以把這些自訂的選項實作完成。
