### ISSUE TITLE
加入XX網域問題

### ISSUE THREAD

**Issue by MAN-GOR** [tongwentang/tongwentang-extension#65]
我使用EDGE瀏覽器進行測試。
在擴充功能裡的新同文堂選項中對某網站選擇「加入XX網域」，然後到另一個網站進行同樣操作，再到網域規則裡看，後者網域會覆蓋掉前者網域，而不是同時保存兩個網域的規則。手動設定則無此問題。

![螢幕擷取畫面 (2)](https://user-images.githubusercontent.com/92726453/205007090-87c27a6d-42e4-4bfb-931d-c7cc584fd9d7.png)

**Comment by t7yang** [comment]
因為這個功能只是讓使用者方便快速地針對某個網域做設定。
對規則而言，一個完全一樣的網域只可能對應一條規則。
所以如果你針對 youtube 做了兩次加入網域的動作，當然就會後者覆寫前者。
我先關掉，如果你有其他疑問，再提出來。

**Comment by MAN-GOR** [comment]
我是指先對「某個」網站做加入動作後，再對「另一個」網站做加入動作，後者的網域會覆寫前者的網域。
例如我先對YouTube做「加入停用網域」，然後再對Twitch做「加入正轉簡網域」，Twitch的網域會覆寫掉YouTube的網域，而不是YouTube和Twitch兩條網域規則同時存在。

**Comment by MAN-GOR** [comment]
已錄製相關操作，並上傳到OneDrive：
https://4hw2w3-my.sharepoint.com/:v:/g/personal/man-gor_4hw2w3_onmicrosoft_com/ERzrvw3vwkZBmPUJSqw0mYsBlgxi59v_bXhAwk2GATjwqA

**Comment by wind571** [comment]
您好，我也遇到相同的問題。
我是用chrome，最近幾個星期發現網域規則只能記錄一個網站，加一個新的進去就會覆蓋原本的，永遠只能一個，想手動加也無法按確定，謝謝。
![111](https://user-images.githubusercontent.com/120474024/207336012-31e4315c-8f5a-4f51-8b9f-c2cf54d68b3c.jpg)
![112](https://user-images.githubusercontent.com/120474024/207336032-896ef5c3-0896-45d5-be06-129c30c87017.jpg)

**Comment by t7yang** [comment]
了解，我會再找時間查明問題，這段時間如果迫不得已，請用匯入組態修改後重新匯入的方式來編輯。
