### ISSUE TITLE
中國百度貼吧，繁體無法轉成簡體，及亂跳位置

### ISSUE THREAD

**Issue by arseela** [tongwentang/tongwentang-extension#8]
◆ 使用 Chrome 89.0.4389.114 
1、沒升級還沒事，一升級之後，在編輯區完全無法轉繁體成簡體 (無論樓中樓還是發主題)
2、在「樓中樓發文區」，除了不能繁轉簡之外，游標還會亂跳位置，沒注意時，打的文字都跑到最前面。

◆ 使用 Firefox 87.0
1、沒升級還沒事，一升級之後，在編輯區完全無法轉繁體成簡體 (無論樓中樓還是發主題)
2、在「樓中樓發文區」及「主題發文區」，除了不能繁轉簡之外，游標還會亂跳位置，沒注意時，打的文字都跑到最前面。

**Comment by Namarimizu** [comment]
確實……這一更新從勉強能用變成了不是很好用，我都想關了……
而且老版本的我手動輸入的一大堆繁簡映射也沒有繼承

**Comment by t7yang** [comment]
> 沒升級還沒事，一升級之後，在編輯區完全無法轉繁體成簡體 (無論樓中樓還是發主題)
請詳述問題如何無法轉換或步驟，必要的話請搭配圖片或影像。另外百度是不可信任的網站，請給他其他網站並給予連結。

然後一個 issue 請回報一個問題。

我先打上 question ，請補充說明你的第一個問題。

第二個問題跟 #10 重複，他只填報一個問題，所以我採計他的 issue 。
這個 issue 我只採計你的第一個問題。
