### ISSUE TITLE
Migrate to WebExtension MV3

### ISSUE THREAD

**Issue by t7yang** [tongwentang/tongwentang-extension#82]
Google 正強迫瀏覽器套件開發使用 MV3 ，這對開發者來說不是一件簡單就能夠遷移的事情，尤其是大型的專案。此專案僅為個人業餘專案，能夠分配的時間有限。目前已開始著手遷移的工作，但不能保證何時能夠完成。

目前僅 Google Chrome 使用者會受到影響，希望各位 Chrome 的使用者能夠見諒。也建議 Chrome 使用者能夠轉用 [Firefox](https://www.mozilla.org/firefox/new/) ——一個開放原始碼（Google Chrome 並非開放原始碼專案）、更加注重隱私、更重要的是並不會有此次強迫停用 MV2 瀏覽器套件的問題。

Google is forcing browser extension developers to use MV3, which is not a simple migration for developers, especially for large projects. This project is just a personal hobby, and the time I can allocate is limited. The migration work has already begun, but I cannot guarantee when it will be completed.

Currently, only Google Chrome users are affected. I hope Chrome users can understand. It is also recommended that Chrome users switch to [Firefox](https://www.mozilla.org/firefox/new/)—an open-source browser (unlike Google Chrome), more focused on privacy, and most importantly, without the issue of being forced to disable MV2 browser extensions.

**Comment by crazykingit** [comment]
no deadline is posted by firefox but they are also asking people to migrate to mv3

**Comment by t7yang** [comment]
@crazykingit the code is shared, so don't worry.
