### ISSUE TITLE
有機會新增 同網站每隔幾秒就重新簡轉正一次嗎?

### ISSUE THREAD

**Issue by chiuchennen** [tongwentang/tongwentang-extension#88]
目前有網站遇到 在下拉選單
或是點按 更多選項 的時候裡面還是簡體的狀況

有沒有機會新增讓使用者自訂每隔幾秒就自動轉正一次嗎?
感謝

**Comment by t7yang** [comment]
不需要，因為動態轉換本身就會偵測內容移動即時進行轉換。
先關閉，有其他想法再提出來。
